// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujTwuHwo7g19ieRmDr1m0j7oQdQJ8cWE',
    appId: '1:483649840304:web:26dbb9bfae5c49c88c4775',
    messagingSenderId: '483649840304',
    projectId: 'taskapp-54b97',
    authDomain: 'taskapp-54b97.firebaseapp.com',
    storageBucket: 'taskapp-54b97.firebasestorage.app',
    measurementId: 'G-MQYBGX11BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABwl-gJtYSvZydISDX4cufM11bS45NpD0',
    appId: '1:483649840304:android:bce72e499d1061e88c4775',
    messagingSenderId: '483649840304',
    projectId: 'taskapp-54b97',
    storageBucket: 'taskapp-54b97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-If0keAaazwIdlpXjR3M2TlUo6hO3kw',
    appId: '1:483649840304:ios:ede419bd3b71d7348c4775',
    messagingSenderId: '483649840304',
    projectId: 'taskapp-54b97',
    storageBucket: 'taskapp-54b97.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv-If0keAaazwIdlpXjR3M2TlUo6hO3kw',
    appId: '1:483649840304:ios:ede419bd3b71d7348c4775',
    messagingSenderId: '483649840304',
    projectId: 'taskapp-54b97',
    storageBucket: 'taskapp-54b97.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDujTwuHwo7g19ieRmDr1m0j7oQdQJ8cWE',
    appId: '1:483649840304:web:242cfb4d146f30fb8c4775',
    messagingSenderId: '483649840304',
    projectId: 'taskapp-54b97',
    authDomain: 'taskapp-54b97.firebaseapp.com',
    storageBucket: 'taskapp-54b97.firebasestorage.app',
    measurementId: 'G-7383P1MCJQ',
  );
}
